{-# LANGUAGE EmptyDataDecls             #-}
{-# LANGUAGE FlexibleContexts           #-}
{-# LANGUAGE GADTs                      #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses      #-}
{-# LANGUAGE OverloadedStrings          #-}
{-# LANGUAGE QuasiQuotes                #-}
{-# LANGUAGE TemplateHaskell            #-}
{-# LANGUAGE TypeFamilies               #-}

module RikardCorp.DBEnum where

import           Database.Persist.TH

data PostStatus = Posted | NotPosted deriving (Show, Read, Eq)

data Okrug =
  TSAO | SAO | SVAO | VAO | YUVAO | YUAO |
  YUZAO | ZAO | SZAO | ZELAO | TINAO deriving (Eq, Show, Enum, Read, Bounded)

data Rayon =
  KIEVSKIJ | FILJOVSKIJ_PARK | NOVOFJODOROVSKOE | ROGOVSKOE | MOSRENTGEN | VORONOVSKOE |
  MIHAJLOVO_JARCEVSKOE | MARUSHKINSKOE | PERVOMAJSKOE | MATUSHKINO | VNUKOVO | SAVJOLKI |
  VNUKOVSKOE | SILINO | KOKOSHKINO | KRJUKOVO | SHHUKINO | KRASNOPAHORSKOE | NAGATINSKIJ_ZATON |
  STAROE_KRJUKOVO | KLJONOVSKOE | DMITROVSKIJ | FILIMONKOVSKOE | TROICK | TJOPLYJ_STAN | SHHAPOVSKOE |
  MOSKOVSKIJ | DESJONOVSKOE | HOVRINO | LOMONOSOVSKIJ | MOZHAJSKIJ | NOVO_PEREDELKINO | STROGINO |
  MOLZHANINOVSKIJ | MITINO | KURKINO | KRYLATSKOE | SOLNCEVO | SOSENSKOE | VOSKRESENSKOE | GOLOVINSKIJ |
  JUZHNOE_TUSHINO | SEVERNOE_TUSHINO | CHERJOMUSHKI | POKROVSKOE_STRESHNEVO | HOROSHJOVO_MNJOVNIKI |
  OCHAKOVO_MATVEEVSKOE | TROPARJOVO_NIKULINO | LEVOBEREZHNYJ | FILI_DAVYDKOVO | OBRUCHEVSKIJ |
  RJAZANOVSKOE | RAMENKI | VOJKOVSKIJ | SOKOL | ZAPADNOE_DEGUNINO | PROSPEKT_VERNADSKOGO |
  JUZHNOE_BUTOVO | JASENEVO | DOROGOMILOVO | KONKOVO | HOROSHJOVSKIJ | BEGOVOJ | KOPTEVO |
  SHHERBINKA | AJEROPORT | PRESNENSKIJ | SEVERNYJ | BESKUDNIKOVSKIJ | GAGARINSKIJ | TIMIRJAZEVSKIJ |
  SEVERNOE_BUTOVO | LIANOZOVO | HAMOVNIKI | VOSTOCHNOE_DEGUNINO | SAVJOLOVSKIJ | AKADEMICHESKIJ |
  ZJUZINO | ALTUFEVSKIJ | MARFINO | CHERTANOVO_CENTRALNOE | OTRADNOE | ARBAT | CHERTANOVO_JUZHNOE |
  BUTYRSKIJ | TVERSKOJ | CHERTANOVO_SEVERNOE | JAKIMANKA | KOTLOVKA | OSTANKINSKIJ | DONSKOJ | BIBIREVO |
  BIRJULJOVO_ZAPADNOE | MARINA_ROSHHA | NAGORNYJ | SVIBLOVO | DANILOVSKIJ | MESHHANSKIJ | JUZHNOE_MEDVEDKOVO |
  ZAMOSKVORECHE | SEVERNOE_MEDVEDKOVO | NAGATINO_SADOVNIKI | MOSKVORECHE_SABUROVO | CARICYNO | BASMANNYJ |
  KRASNOSELSKIJ | ROSTOKINO | TAGANSKIJ | ALEKSEEVSKIJ | SOKOLNIKI | BIRJULJOVO_VOSTOCHNOE | BABUSHKINSKIJ |
  JUZHNOPORTOVYJ | JAROSLAVSKIJ | PECHATNIKI | BOGORODSKOE | METROGORODOK | LEFORTOVO | OREHOVO_BORISOVO_SEVERNOE |
  LOSINOOSTROVSKIJ | NIZHEGORODSKIJ | PEROVO | OREHOVO_BORISOVO_JUZHNOE | MARINO | VESHNJAKI | PREOBRAZHENSKOE |
  SOKOLINAJA_GORA | LJUBLINO | TEKSTILSHHIKI | BRATEEVO | ZJABLIKOVO | RJAZANSKIJ | IZMAJLOVO | NOVOGIREEVO |
  KUZMINKI | GOLJANOVO | SEVERNOE_IZMAJLOVO | KAPOTNJA | VYHINO_ZHULEBINO | VOSTOCHNYJ | VOSTOCHNOE_IZMAJLOVO |
  IVANOVSKOE | KOSINO_UHTOMSKIJ | NOVOKOSINO | NEKRASOVKA | KUNCEVO deriving (Eq, Show, Enum, Read, Bounded)

data Ploshad =
  P1_50 | P50_100 | P100_200 | P200_500 |
  P500_1000 | P1000_10000 | P10000_100000 deriving (Eq, Show, Enum, Ord, Read, Bounded)

data Naznachenie =
  OFIS | TORGOVAJA_PLOSHHAD | SKLAD | OBSHHEPIT | SVOBODNOE_NAZNACHENIE | AVTOSTOJANKA |
  PROIZVODSTVO | AVTOSERVIS | GOTOVYJ_BIZNES | OTDELNO_STOJASHHEE_ZDANIE | BYTOVYE_USLUGI |
  MEDICINA | KULTURNOE_NASLEDIE | GOSTINICA | ZEMELNYJ_UCHASTOK | RAZRESHENA_SUBARENDA | PRODAZHA_PPA |
  GARAZH | KINOTEATR | APTEKA | DOKTOR_RJADOM | KAFE | RESTORAN | STOLOVAJA | MAGAZIN | AVTOSALON |
  BANK | FOK | REKLAMNAJA_PLOSHHAD | DOU | OBRAZOVATELNOE | NEZHILOE | JEKSKLJUZIV | SOBSTVENNOST |
  AVTOMOJKA | NOCHNOJ_KLUB | KVARTIRA | PRJAMAJA_ARENDA | MASHINOMESTO deriving (Eq, Show, Enum, Read, Bounded)

derivePersistField "PostStatus"
derivePersistField "Okrug"
derivePersistField "Rayon"
derivePersistField "Ploshad"
derivePersistField "Naznachenie"
